version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      PACKAGE_DIR: nx_arangodb
      TESTS_DIR: tests

  machine-executor:
    machine:
      image: ubuntu-2404:2024.05.1

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Setup pip
          command: python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: Run black
          command: black --check --verbose --diff --color $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run flake8
          command: flake8 $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run isort
          command: isort --check --profile=black $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run mypy
          command: mypy $PACKAGE_DIR $TESTS_DIR

  test:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Set up ArangoDB
          command: |
            chmod +x starter.sh
            ./starter.sh

      - run:
          name: Setup Python
          command: |
            pyenv --version
            pyenv install -f 3.10
            pyenv global 3.10

      - run:
          name: Setup pip
          command: python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: Run local tests
          command: pytest tests/test.py

      - run:
          name: Run NetworkX tests
          command: ./run_nx_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test