version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      PACKAGE_DIR: nx_arangodb
      TESTS_DIR: tests

  machine-executor:
    machine:
      image: ubuntu-2404:current

  gpu-executor:
    machine:
      image: linux-cuda-12:default
    resource_class: gpu.nvidia.small.multi

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Setup pip
          command: python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: Run black
          command: black --check --verbose --diff --color $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run flake8
          command: flake8 $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run isort
          command: isort --check --profile=black $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run mypy
          command: mypy $PACKAGE_DIR $TESTS_DIR

  test:
    parameters:
      python_version:
        type: string
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Set up ArangoDB
          command: |
            chmod +x starter.sh
            ./starter.sh

      - run:
          name: Setup Python
          command: |
            pyenv --version
            pyenv install -f << parameters.python_version >>
            pyenv global << parameters.python_version >>

      - run:
          name: Setup pip
          command: python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: Run local tests
          command: pytest tests/*.py

      - run:
          name: Run NetworkX tests
          command: ./run_nx_tests.sh

  test-gpu:
    parameters:
      python_version:
        type: string
    executor: gpu-executor
    steps:
      - checkout

      - run:
          name: Set up ArangoDB
          command: |
            chmod +x starter.sh
            ./starter.sh

      - run:
          name: Setup Python
          command: |
            pyenv --version
            pyenv install -f << parameters.python_version >>
            pyenv global << parameters.python_version >>

      - run:
          name: Create virtual environment
          command: python -m venv venv

      - run:
          name: Activate virtual environment
          command: . venv/bin/activate

      - run:
          name: Setup pip
          command: venv/bin/python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: venv/bin/pip install .[dev]

      - run:
          name: Install cuda related dependencies
          command: |
            venv/bin/pip install pylibcugraph-cu12 --extra-index-url https://pypi.nvidia.com
            venv/bin/pip install nx-cugraph-cu12 --extra-index-url https://pypi.nvidia.com

      - run:
          name: Run local gpu tests
          command: venv/bin/pytest tests/test.py -k "test_gpu" --run-gpu-tests

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              python_version: ["3.10", "3.11", "3.12"]
      - test-gpu:
          requires:
            - lint
            - test
          matrix:
            parameters:
              python_version: ["3.10", "3.11"] # "3.12" # TODO: Revisit 3.12
          filters:
            branches:
              only:
                - main