version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    environment:
      PACKAGE_DIR: nx_arangodb
      TESTS_DIR: tests

  machine-executor:
    machine:
      image: ubuntu-2204:2024.01.1

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Setup pip
          command: python -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: Run black
          command: black --check --verbose --diff --color $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run flake8
          command: flake8 $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run isort
          command: isort --check --profile=black $PACKAGE_DIR $TESTS_DIR

      - run:
          name: Run mypy
          command: mypy $PACKAGE_DIR $TESTS_DIR

  test:
    executor: machine-executor
    steps:
      - checkout

      - run:
          name: Setup Python 3.10
          command: sudo apt-get update && sudo apt-get install -y python3.10 python3.10-venv python3.10-dev

      - run:
          name: Install System Dependencies
          command: sudo apt-get install -y libssl-dev libffi-dev

      - run:
          name: Setup pip
          command: python3.10 -m pip install --upgrade pip setuptools wheel

      - run:
          name: Install packages
          command: pip install .[dev]

      - run:
          name: List files
          command: ls -alh

      - run:
          name: Install Phenolrs (temporary solution)
          #command: pip install phenolrs --find-links .
          command: pip install ./phenolrs-0.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl --verbose

      - run:
          name: Set up ArangoDB
          command: |
            chmod +x starter.sh
            ./starter.sh

      - run:
          name: Run local tests
          command: pytest tests/test.py

      - run:
          name: Run NetworkX tests
          command: ./run_nx_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test:
          requires:
            - lint