blank_issues_enabled: true
contact_links:
  - name: Questions about NetworkX-ArangoDB
    url: https://github.com/arangodb/nx-arangodb/discussions/new?category=q-a
    about: Ask questions about usage of NetworkX-ArangoDB
  - name: Discussions and Ideas
    url: https://github.com/arangodb/nx-arangodb/discussions
    about: Talk about new algorithms, feature requests, show your latest application of networks.
