name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

env:
  PACKAGE_DIR: nx_arangodb
  TESTS_DIR: tests

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Setup pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install packages
        run: pip install .[dev]

      - name: Run black
        run: black --check --verbose --diff --color ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}

      - name: Run flake8
        run: flake8 ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}

      - name: Run isort
        run: isort --check --profile=black ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}

      - name: Run mypy
        run: mypy ${{env.PACKAGE_DIR}} ${{env.TESTS_DIR}}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Set up ArangoDB
        run: |
          chmod +x starter.sh
          ./starter.sh

      - name: Setup pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install packages
        run: pip install .[dev]

      - name: Install Phenolrs (temporary solution)
        run: pip install phenolrs --find-links .

      - name: Run local tests
        run: pytest tests/test.py

      - name: Run NetworkX tests
        run: ./run_nx_tests.sh
